---
- hosts: all
  gather_facts: false 
  vars_prompt:
  - name: password
    prompt: "Enter local administrator password"

  vars:
    ansible_user: root
    ansible_password: "{{ password }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
  - name: run ping
    ping:


