---
- name: Install prerequisites 
  become: true 
  apt: 
    pkg:
    - apt-transport-https
    - software-properties-common
    state: present
    update_cache: yes

- name: Add grafana official keys
  become: true 
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: setup stable repository 
  become: true 
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install the latest grafana OSS packages 
  become: true
  apt:
    pkg: 
    - grafana
    state: latest
    update_cache: yes 



