---
- name: Install packages needed for loki
  become: true
  ansible.builtin.yum:
    name:
    - unzip
    state: latest
    update_cache: true

- name: Create Loki user 
  become: true 
  ansible.builtin.user:
    name: loki
    shell: /bin/bash 
    system: yes
    state: present
    comment: Loki server owner

- name: Make sure the needed directories exist in the system 
  become: true 
  ansible.builtin.file: 
    path: /etc/loki/
    owner: loki
    group: loki 
    state: directory 
    recurse: yes

- name: Download the loki package to /usr/local/bin 
  become: true
  tags: loki 
  ansible.builtin.unarchive: 
    src: "https://github.com/grafana/loki/releases/download/v{{ version }}/loki-{{ arch }}.zip" 
    dest: /etc/loki/
    owner: loki
    group: loki
    remote_src: yes 

- name: Download the promtail package to /usr/local/bin
  become: true
  tags: promtail
  ansible.builtin.unarchive:
    src: "https://github.com/grafana/loki/releases/download/v{{ version }}/promtail-{{ arch }}.zip"
    dest: /etc/loki/
    owner: loki
    group: loki
    remote_src: yes

- name: Download loki configuration file
  become: true
  tags: loki 
  ansible.builtin.get_url: 
    url: "https://raw.githubusercontent.com/grafana/loki/master/cmd/loki/loki-local-config.yaml"
    dest: /etc/loki/
    owner: loki
    group: loki

- name: Download promtail configuration file
  become: true 
  tags: promtail
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/grafana/loki/main/clients/cmd/promtail/promtail-local-config.yaml"
    dest: /etc/loki/
    owner: loki
    group: loki
